# Generated by Django 5.0.2 on 2024-08-27 13:40

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('status', models.BooleanField()),
                ('state_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('shortname', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('icon', models.ImageField(blank=True, upload_to='faculty/')),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('state_description', models.TextField(help_text='Reason for the status to be true or false', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
                ('state_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('shortname', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('shortname', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='departements/')),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.SmallIntegerField(default=0)),
                ('status', models.BooleanField()),
                ('state_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.building')),
            ],
            options={
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.SmallIntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.general')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('shortname', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('icon', models.ImageField(blank=True, upload_to='programs/')),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('exm_capacity', models.PositiveIntegerField(default=0)),
                ('usable_for_exm', models.BooleanField(default=True, help_text='if the room can be use for exam')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('room_type', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('SEM', 'Seminar'), ('STU', 'Studio'), ('WOR', 'Workshop'), ('OFF', 'Office'), ('OTH', 'Other')], max_length=4)),
                ('status', models.BooleanField()),
                ('state_description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.floor')),
                ('room_feature', models.ManyToManyField(to='apibase.roomfeatures')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2023-2024', max_length=10)),
                ('season', models.CharField(choices=[('SPRING', 'Spring'), ('FALL', 'Fall'), ('SUMMER', 'Summer')], max_length=6)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_num', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('status', models.BooleanField(default=True)),
                ('program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.SmallIntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.general')),
            ],
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('source', models.BigIntegerField(null=True)),
                ('origin', models.CharField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.end')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.start')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('deleted', models.BooleanField(default=False)),
                ('department', models.ManyToManyField(to='apibase.department')),
                ('faculty', models.ManyToManyField(to='apibase.faculty')),
                ('program', models.ManyToManyField(to='apibase.program')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.title')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
