# Generated by Django 5.0.2 on 2024-02-26 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_adminoperationsP', 'Can view admin operations'), ('edit_preferences_adminoperationsP', 'Can edit preferences of other users')],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='apibase.users')),
                ('lecturerid', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='apibase.users')),
                ('stafftype', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='apibase.users')),
                ('studentId', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('current_capacity', models.PositiveSmallIntegerField(default=0)),
                ('waitinglist', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('duration', models.TextField(null=True)),
                ('max_capacity', models.SmallIntegerField(default=0)),
                ('is_elective', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ManyToManyField(to='apibase.activitytype')),
                ('course_semester', models.ManyToManyField(blank=True, to='apibase.coursesemester')),
                ('extra_session_of', models.ManyToManyField(blank=True, to='apibase.course')),
                ('merged_with', models.ManyToManyField(blank=True, to='apibase.course')),
                ('prerequisites', models.ManyToManyField(blank=True, to='apibase.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.users')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture', to='apibase.lecturer')),
                ('lecturer_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lecturer_Assisting', to='apibase.lecturer')),
                ('otherstaff', models.ManyToManyField(blank=True, to='apibase.otherstaff')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assisting', to='apibase.student')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.general')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False)),
                ('position', models.IntegerField(help_text='Position of the preference in the owner order of preferences', null=True)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.building')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.course')),
                ('course_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.coursesemester')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.department')),
                ('event_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.eventtime')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.faculty')),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.floor')),
                ('general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.general')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.program')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.room')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Generalpref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.general')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='Floorpref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.floor')),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='Facultypref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.faculty')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='EventTimepref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.eventtime')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='Departmentpref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.department')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSemesterPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.coursesemester')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.course')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='Buildingpref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.building')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
            ],
        ),
        migrations.CreateModel(
            name='Programpref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.program')),
            ],
        ),
        migrations.CreateModel(
            name='Roompref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.room')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.preference')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.semester')),
            ],
        ),
    ]
