# Generated by Django 5.0.2 on 2024-09-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_adminoperationsP', 'Can view admin operations'), ('edit_preferences_adminoperationsP', 'Can edit preferences of other users')],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='apibase.users')),
                ('lecturerid', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='apibase.users')),
                ('stafftype', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='apibase.users')),
                ('studentId', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.users')),
                ('other_staff', models.ManyToManyField(blank=True, to='apibase.otherstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.general')),
            ],
        ),
        migrations.CreateModel(
            name='Coursegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveSmallIntegerField(default=1)),
                ('duration', models.TextField(null=True)),
                ('current_capacity', models.PositiveSmallIntegerField(default=0)),
                ('max_capacity', models.SmallIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activitytype', models.ManyToManyField(to='apibase.activitytype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='apibase.course')),
                ('course_semester', models.ManyToManyField(to='apibase.coursesemester')),
                ('extra_session_of', models.ManyToManyField(to='apibase.coursegroup')),
                ('merged_with', models.ManyToManyField(to='apibase.coursegroup')),
                ('prerequisites', models.ManyToManyField(related_name='requiredCourse', to='apibase.course')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.lecturer')),
                ('lecturer_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lecturer_Assisting', to='apibase.lecturer')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.student')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(default=0, help_text='To know the orientation for the pref wether it is positive, negative, or neutral')),
                ('position', models.IntegerField(help_text='Position of the preference in the owner order of preferences', null=True)),
                ('description', models.TextField(null=True)),
                ('start', models.CharField(null=True)),
                ('end', models.CharField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.BooleanField()),
                ('origin', models.CharField(choices=[('general', 'general'), ('building', 'building'), ('floor', 'floor'), ('room', 'room'), ('faculty', 'faculty'), ('department', 'department'), ('course_semester', 'course_semester'), ('course', 'course'), ('semester', 'semester'), ('course', 'course'), ('coursegroup', 'coursegroup'), ('event_time', 'event_time'), ('title', 'title'), ('general', 'general')], max_length=255)),
                ('originId', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ManyToManyField(blank=True, to='apibase.activitytype')),
                ('building', models.ManyToManyField(blank=True, to='apibase.building')),
                ('course', models.ManyToManyField(blank=True, to='apibase.course')),
                ('course_semester', models.ManyToManyField(blank=True, to='apibase.coursesemester')),
                ('coursegroup', models.ManyToManyField(blank=True, to='apibase.coursegroup')),
                ('department', models.ManyToManyField(blank=True, to='apibase.department')),
                ('event_time', models.ManyToManyField(blank=True, to='apibase.eventtime')),
                ('faculty', models.ManyToManyField(blank=True, to='apibase.faculty')),
                ('floor', models.ManyToManyField(blank=True, to='apibase.floor')),
                ('general', models.ManyToManyField(blank=True, to='apibase.general')),
                ('lecturer', models.ManyToManyField(blank=True, to='apibase.lecturer')),
                ('program', models.ManyToManyField(blank=True, to='apibase.program')),
                ('room', models.ManyToManyField(blank=True, to='apibase.room')),
                ('room_features', models.ManyToManyField(blank=True, to='apibase.roomfeatures')),
                ('semester', models.ManyToManyField(blank=True, to='apibase.semester')),
                ('title', models.ManyToManyField(blank=True, to='apibase.title')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.users')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespan', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('coursegroup', models.ManyToManyField(related_name='studentgroups', to='apibase.coursegroup')),
                ('student', models.ManyToManyField(to='apibase.student')),
            ],
        ),
    ]
