# Generated by Django 5.0.2 on 2024-04-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0002_activitytype_adminoperations_lecturer_otherstaff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apibase.users'),
            preserve_default=False,
        ),
    ]
