# Generated by Django 5.0.2 on 2024-09-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0002_activitytype_adminoperations_lecturer_otherstaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
