# Generated by Django 5.0.2 on 2024-02-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0002_activitytype_adminoperations_lecturer_otherstaff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='activity_type',
            new_name='activitytype',
        ),
    ]
