# Generated by Django 5.0.2 on 2024-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0003_rename_activity_type_course_activitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(default='2023-2024', max_length=10),
        ),
    ]
