# Generated by Django 5.0.2 on 2024-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0003_alter_activitytype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('name', 'code')},
        ),
    ]
