# Generated by Django 5.0.2 on 2024-04-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0003_preference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='coursegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.coursegroup'),
        ),
    ]
