# Generated by Django 5.0.2 on 2024-02-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0004_alter_semester_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='activitytype',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='course',
            name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='extra_session_of',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer_assistant',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='merged_with',
        ),
        migrations.RemoveField(
            model_name='course',
            name='waitinglist',
        ),
        migrations.CreateModel(
            name='Coursegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveSmallIntegerField(default=1)),
                ('duration', models.TextField(null=True)),
                ('current_capacity', models.PositiveSmallIntegerField(default=0)),
                ('max_capacity', models.SmallIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activitytype', models.ManyToManyField(to='apibase.activitytype')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.course')),
                ('extra_session_of', models.ManyToManyField(blank=True, to='apibase.coursegroup')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.lecturer')),
                ('lecturer_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lecturer_Assisting', to='apibase.lecturer')),
                ('merged_with', models.ManyToManyField(blank=True, to='apibase.coursegroup')),
            ],
        ),
    ]
