# Generated by Django 5.0.2 on 2024-09-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0004_alter_building_code_alter_building_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_feature',
            field=models.ManyToManyField(blank=True, to='apibase.roomfeatures'),
        ),
    ]
