# Generated by Django 5.0.2 on 2024-04-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0004_preference_coursegroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'season')},
        ),
    ]
