# Generated by Django 5.0.2 on 2024-02-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0005_remove_course_activitytype_remove_course_assistant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course_semester',
            field=models.ManyToManyField(blank=True, to='apibase.coursesemester'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='apibase.coursegroup'),
        ),
    ]
