# Generated by Django 5.0.2 on 2024-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0005_alter_semester_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='otherstaff',
            new_name='other_staff',
        ),
    ]
