# Generated by Django 5.0.2 on 2024-02-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0006_remove_course_course_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesemester',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.faculty'),
        ),
    ]
