# Generated by Django 5.0.2 on 2024-09-16 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0006_alter_department_name_alter_department_shortname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesemester',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesemester',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursesemester',
            unique_together={('program', 'semester', 'semester_num')},
        ),
    ]
