# Generated by Django 5.0.2 on 2024-09-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0007_coursesemester_created_at_coursesemester_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='department',
        ),
        migrations.RemoveField(
            model_name='users',
            name='faculty',
        ),
    ]
