# Generated by Django 5.0.2 on 2024-03-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0007_coursesemester_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='course_semester',
            field=models.ManyToManyField(blank=True, null=True, to='apibase.coursesemester'),
        ),
    ]
