# Generated by Django 5.0.2 on 2024-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0008_alter_coursegroup_course_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegroup',
            old_name='course_semester',
            new_name='coursesemester',
        ),
    ]
