# Generated by Django 5.0.2 on 2024-03-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0009_rename_course_semester_coursegroup_coursesemester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegroup',
            old_name='coursesemester',
            new_name='course_semester',
        ),
    ]
