# Generated by Django 5.0.2 on 2024-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0009_rename_title_course_name_alter_users_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='extra_session_of',
            field=models.ManyToManyField(blank=True, to='apibase.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='merged_with',
            field=models.ManyToManyField(blank=True, to='apibase.coursegroup'),
        ),
        migrations.AlterField(
            model_name='users',
            name='credential',
            field=models.CharField(choices=[('SYSADM', 'SystemAdmin'), ('PADM', 'PlatformAdmin'), ('VR', 'ViceRector'), ('AD', 'Advisor'), ('HOD', 'HeadOfDepartment'), ('ASS', 'Assistant'), ('OT', 'Other')], default='OT', max_length=255),
        ),
    ]
