# Generated by Django 5.0.2 on 2024-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0009_remove_coursepref_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='building',
            field=models.ManyToManyField(blank=True, to='apibase.building'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='course',
            field=models.ManyToManyField(blank=True, to='apibase.course'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='course_semester',
            field=models.ManyToManyField(blank=True, to='apibase.coursesemester'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='coursegroup',
            field=models.ManyToManyField(blank=True, to='apibase.coursegroup'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='department',
            field=models.ManyToManyField(blank=True, to='apibase.department'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='event_time',
            field=models.ManyToManyField(blank=True, to='apibase.eventtime'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='apibase.faculty'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='floor',
            field=models.ManyToManyField(blank=True, to='apibase.floor'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='general',
            field=models.ManyToManyField(blank=True, to='apibase.general'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='program',
            field=models.ManyToManyField(blank=True, to='apibase.program'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='room',
            field=models.ManyToManyField(blank=True, to='apibase.room'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='semester',
            field=models.ManyToManyField(blank=True, to='apibase.semester'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='title',
            field=models.ManyToManyField(blank=True, to='apibase.title'),
        ),
    ]
