# Generated by Django 5.0.2 on 2024-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0010_alter_coursegroup_extra_session_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='requiredCourse', to='apibase.course'),
        ),
    ]
