# Generated by Django 5.0.2 on 2024-05-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0010_alter_preference_building_alter_preference_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
