# Generated by Django 5.0.2 on 2024-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0010_rename_coursesemester_coursegroup_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='course_semester',
            field=models.ManyToManyField(to='apibase.coursesemester'),
        ),
    ]
