# Generated by Django 5.0.2 on 2024-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0011_alter_coursegroup_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='extra_session_of',
            field=models.ManyToManyField(to='apibase.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='merged_with',
            field=models.ManyToManyField(to='apibase.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='prerequisites',
            field=models.ManyToManyField(related_name='requiredCourse', to='apibase.course'),
        ),
    ]
