# Generated by Django 5.0.2 on 2024-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0011_preference_date_preference_end_preference_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='end',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='start',
            field=models.CharField(null=True),
        ),
    ]
