# Generated by Django 5.0.2 on 2024-09-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0011_alter_coursegroup_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('coursegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_coursegroup', to='apibase.coursegroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_room', to='apibase.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.users')),
            ],
        ),
    ]
