# Generated by Django 5.0.2 on 2024-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0012_schedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('room', 'start', 'end', 'day'), name='unique_room_day_time'),
        ),
    ]
