# Generated by Django 5.0.2 on 2024-09-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0013_schedule_unique_room_day_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_lecturer', to='apibase.lecturer'),
        ),
    ]
