# Generated by Django 5.0.2 on 2024-09-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0014_alter_lecturer_user'),
        ('apibase', '0015_schedule_created_at_schedule_status_and_more'),
    ]

    operations = [
    ]
