# Generated by Django 5.0.2 on 2024-09-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0018_advisor_student_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to='apibase.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='coursegroup',
            field=models.ManyToManyField(blank=True, null=True, to='apibase.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.users'),
        ),
    ]
