# Generated by Django 5.0.2 on 2024-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0019_remove_advisor_lecturer_advisor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
