# Generated by Django 5.0.2 on 2024-10-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0020_alter_course_code'),
        ('apibase', '0020_alter_student_user'),
    ]

    operations = [
    ]
