# Generated by Django 5.0.2 on 2024-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0021_merge_0020_alter_course_code_0020_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnews',
            name='type',
            field=models.CharField(choices=[('sys', 'system'), ('lect', 'lecture')], default='sys', max_length=255),
        ),
    ]
