# Generated by Django 5.0.2 on 2024-10-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0022_systemnews_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('can_std_view', models.BooleanField(default=False)),
                ('can_lect_view', models.BooleanField(default=False)),
                ('can_adv_view', models.BooleanField(default=False)),
                ('can_hod_view', models.BooleanField(default=False)),
                ('can_vcr_view', models.BooleanField(default=False)),
                ('can_padm_view', models.BooleanField(default=False)),
                ('can_system_view', models.BooleanField(default=False)),
                ('can_asst_view', models.BooleanField(default=False)),
                ('can_other_view', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
