# Generated by Django 5.0.2 on 2024-10-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0023_scheduletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apibase.scheduletype'),
            preserve_default=False,
        ),
    ]
