# Generated by Django 5.0.2 on 2024-10-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0024_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coursegroup',
            field=models.ManyToManyField(blank=True, to='apibase.coursegroup'),
        ),
    ]
