# Generated by Django 5.0.2 on 2024-10-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0024_schedule_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='assistant',
        ),
        migrations.AlterField(
            model_name='student',
            name='coursegroup',
            field=models.ManyToManyField(blank=True, to='apibase.coursegroup'),
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursegroup', models.ManyToManyField(to='apibase.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibase.student')),
            ],
        ),
    ]
