# Generated by Django 5.0.2 on 2024-10-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0025_remove_coursegroup_assistant_and_more'),
        ('apibase', '0027_schedule_type'),
    ]

    operations = [
    ]
