# Generated by Django 5.0.2 on 2024-11-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0028_merge_20241014_2130'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_room_day_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibase.lecturer'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('room', 'start', 'end', 'day', 'type'), name='unique_room_day_time_time'),
        ),
    ]
