# Generated by Django 5.0.2 on 2025-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0029_remove_schedule_unique_room_day_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
