# Generated by Django 5.0.2 on 2025-02-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0030_semester_is_current'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_room_day_time_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apibase.semester'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('room', 'start', 'end', 'day', 'type', 'semester'), name='unique_room_day_time_time'),
        ),
    ]
