# Generated by Django 5.0.2 on 2025-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0031_remove_schedule_unique_room_day_time_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='course_semester',
            field=models.ManyToManyField(related_name='course_groups', to='apibase.coursesemester'),
        ),
    ]
